### ISSUE TITLE
Upload a new appartement on database (Scott)

### ISSUE THREAD

**Issue by jules20022000** [host-me-app/host-me#10]
## Phase 1:  
Research requirements of a residence listing & determine where in FireBase to set schema and store additional fields such as photos.
- _complete_
## Phase 2:  
Create `appartement` schema (JSON?) for database and `appartement` class to consume the schema within the app.
- _complete_
## Phase 3:  
Upload a dummy `appartement` to the db
- _complete_

**Comment by Scott2Williams** [comment]
The FireStore collection for apartments will now be enforced by the required fields of the `apartments.json` schema.

> _NOTE:_ The document naming schema of the dummy apartment object does not reflect the generation of `lid`s that will be used from now on. FireBase randomly generated IDs will be used and this document will be deleted once the apartment generation form is implemented.
